name: Publish to npm

on:
  push:
    branches:
      - main  # only run when code is merged into main
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check last commit message
        id: check_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" =~ chore:\ upgrade ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
          else
            echo "match=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.check_commit.outputs.match == 'true'
        run: npm ci

      - name: Publish to npm
        if: steps.check_commit.outputs.match == 'true'
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}