name: Update 7zip binaries

on:
  push:
    branches:
      - auto-update-action
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 6 * * *' # Daily

permissions:
  contents: write # to create release (changesets/action)
  pull-requests: write # to create pull request (changesets/action)

jobs:
  update-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install -g @changesets/cli @changesets/cli/commit @changesets/changelog-github
          npm install

      - name: Run update binaries script
        id: update
        run: node update-binaries.js --publish

      - name: Get 7zip version
        id: version
        run: |
          echo "version=$(cat 7z-version.txt)" >> $GITHUB_OUTPUT
          rm 7z-version.txt

      - name: Get package version
        id: packageVersion
        run: |
          echo "version=$(cat package-version.txt)" >> $GITHUB_OUTPUT
          rm package-version.txt

      - name: Bump version with npm
        run: npm version ${{ steps.packageVersion.outputs.version }} --no-git-tag-version

      - name: Create Pull Request with changesets/action
        uses: changesets/action@v1
        with:
          version: changeset version
          title: "chore: upgrade 7zip binaries to v${{ steps.version.outputs.version }}"
          commit: "chore: upgrade 7zip binaries to v${{ steps.version.outputs.version }}"
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}