name: Run update binaries script and open pull request

on:
  push:
    branches:
      - auto-update-action
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 6 * * *' # Daily

permissions:
  contents: write # to create release (changesets/action)
  pull-requests: write # to create pull request (changesets/action)

jobs:
  update-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Install dependencies
        run: |
          npm install -g @changesets/cli @changesets/changelog-github
          npm install

      - name: Run update binaries script
        id: update
        run: node update-binaries.js --publish

      - name: Get 7zip version
        id: version
        run: |
          echo "version=$(cat 7z-version.txt)" >> $GITHUB_OUTPUT
          rm 7z-version.txt

      - name: Get package version
        id: packageVersion
        run: |
          echo "version=$(cat package-version.txt)" >> $GITHUB_OUTPUT
          rm package-version.txt

      - name: Bump version with pnpm
        run: pnpm version ${{ steps.packageVersion.outputs.version }} --no-git-tag-version

      - name: Create Pull Request with changesets/action
        uses: changesets/action@v1
        with:
          version: |
            changeset version
            pnpm version ${{ steps.packageVersion.outputs.version }} --no-git-tag-version
            node update-version.js ${{ steps.packageVersion.outputs.version }}
            node -e "const fs = require('node:fs'); const readme = fs.readFileSync('./README.md', 'utf8'); fs.writeFileSync(readme.replace(/## (\d+\.\d+\.\d+)/, '## ${{ steps.packageVersion.outputs.version }}'), 'utf8');"
          title: "chore: upgrade 7zip binaries to v${{ steps.version.outputs.version }}"
          commit: "chore: upgrade 7zip binaries to v${{ steps.version.outputs.version }}"
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}